Repository Simply-Love/Simply-Love-SM5, pull requests merged in 2021-01, with the labels that each got.

#240 Add whole _wendy small [alt] glyph block
  Fonts/Wendy/_wendy small [alt] 10x10 (doubleres).png
  Fonts/Wendy/_wendy small.ini
Labels: enhancement

#232 Make the timestamp in screen eval and eval summary update
  BGAnimations/ScreenSystemLayer overlay.lua
Labels: enhancement

#241 bug fix: group durations on ScreenSelectMusic
  BGAnimations/ScreenSelectMusic overlay/PreserveMenuTimer.lua
  BGAnimations/ScreenSelectMusic overlay/SongDescription/GroupDurations.lua
  BGAnimations/ScreenSelectMusic overlay/SongDescription/SongDescription.lua
  BGAnimations/ScreenSelectMusic overlay/default.lua
  BGAnimations/ScreenSelectMusic overlay/playerModifiers.lua
Labels: bug

#234 Use correct translation strings for casual mode song description
  BGAnimations/ScreenSelectMusic overlay/SongDescription/SongDescription.lua
  BGAnimations/ScreenSelectMusicCasual overlay/SongWheelShared.lua
  Languages/de.ini
  Languages/en.ini
  Languages/es.ini
  Languages/fr.ini
  Languages/it.ini
  Languages/ja.ini
  Languages/pt-br.ini
Labels: bug

#246 bug fix: _wendy small's import
  Fonts/Wendy/_wendy small.ini
Labels: bug

#247 add NoRolls mod to Uncommon Modifiers as "Rolls to Holds"
  Languages/en.ini
  metrics.ini
Labels: new feature

#245 bug fix: don't diffuse emoji in OptionRow Titles
  metrics.ini
Labels: bug

#244 make better use of SFX on SelectMusicCasual
  BGAnimations/ScreenSelectMusicCasual overlay/Input.lua
  BGAnimations/ScreenSelectMusicCasual overlay/SoundEffects.lua
  BGAnimations/ScreenSelectMusicCasual overlay/default.lua
Labels: enhancement

#243 bug fix: OptionRows being hidden in ScreenManageProfiles MiniMenu (#230)
  metrics.ini
Labels: bug
