Repository Simply-Love/Simply-Love-SM5, pull requests merged in 2021-05, with the labels that each got.

#292 Also hide the colorful bar after a while when multi-tick is enabled
  BGAnimations/ScreenGameplay underlay/PerPlayer/ErrorBar/Colorful.lua
  Languages/en.ini
Labels: bug

#315 Fix chart parser for autogen charts
  Scripts/SL-ChartParser.lua
Labels: bug

#314 Clear stream data if we can't parse a chart
  BGAnimations/ScreenSelectMusic overlay/PerPlayer/DensityGraph.lua
  Scripts/SL-ChartParser.lua
  Scripts/SL-ChartParserHelpers.lua
Labels: bug

#313 Add option for turning keyboard features on or off
  BGAnimations/ScreenSelectMusic overlay/SortMenu/default.lua
  Languages/en.ini
  Scripts/99 SL-ThemePrefs.lua
  metrics.ini
Labels: bug, enhancement

#318 Only show the GS high score if it's higher than the local one
  BGAnimations/ScreenSelectMusic overlay/PaneDisplay.lua
Labels: enhancement

#316 Fix "COUNTS AS 2 ROUNDS" bubble position
  BGAnimations/ScreenSelectMusic overlay/SongDescription/SongDescription.lua
Labels: bug

#321 Fix GS player scores
  BGAnimations/ScreenSelectMusic overlay/PaneDisplay.lua
Labels: bug

#324 Fix GrooveStats.ini loading for USB profiles
  BGAnimations/ScreenSelectMusic overlay/PaneDisplay.lua
  Scripts/SL-PlayerProfiles.lua
Labels: bug
